
/*
 * Cursor 汉化脚本
 * Auto-generated by Cursor_Localization_Tool.py
 * Generated: __BUILD_TIMESTAMP__

 */
(function() {
    'use strict';

    // 从旧版 cursor_hanhua_* 键名迁移 localStorage（一次性）
    (function Migrate_Cursor_Localization_Storage() {
        var pairs = [
            ['cursor_hanhua_market_translate', 'Cursor_Localization_Market_Translate'],
            ['cursor_hanhua_market_online_translate', 'Cursor_Localization_Market_Online_Translate']
        ];
        var obsoleteKeys = [
            'cursor_hanhua_market_toggle_hidden',
            'cursor_hanhua_market_toggle_pos',
            'Cursor_Localization_Market_Toggle_Hidden',
            'Cursor_Localization_Market_Toggle_Pos'
        ];
        try {
            for (var oi = 0; oi < obsoleteKeys.length; oi++) {
                try { localStorage.removeItem(obsoleteKeys[oi]); } catch (e) {}
            }
            for (var i = 0; i < pairs.length; i++) {
                var oldK = pairs[i][0], newK = pairs[i][1];
                var v = localStorage.getItem(oldK);
                if (v !== null) {
                    if (localStorage.getItem(newK) === null) localStorage.setItem(newK, v);
                    localStorage.removeItem(oldK);
                }
            }
            var prefixOld = 'cursor_hanhua_market_cache_';
            var prefixNew = 'Cursor_Localization_Market_Cache_';
            var keys = [];
            for (var j = 0; j < localStorage.length; j++) {
                var k = localStorage.key(j);
                if (k) keys.push(k);
            }
            for (var n = 0; n < keys.length; n++) {
                var key = keys[n];
                if (key.indexOf(prefixOld) === 0) {
                    var nk = prefixNew + key.slice(prefixOld.length);
                    var val = localStorage.getItem(key);
                    if (val !== null && localStorage.getItem(nk) === null) localStorage.setItem(nk, val);
                    localStorage.removeItem(key);
                }
            }
        } catch (e) {}
    })();

    // ================================================================
    // SECTION 1: 翻译字典
    // ================================================================

    // __CORE_DICTIONARY_BLOCK__

    // __MERGE_GUANGGAO_TANCHUANG__

    // __PATTERN_DICTIONARY_BLOCK__
